import unicorn from 'eslint-plugin-unicorn';
import ava from 'eslint-plugin-ava';
import n from 'eslint-plugin-n';
import noNative from 'eslint-plugin-no-use-extend-native';
import comments from 'eslint-plugin-eslint-comments';
import sonarjs from 'eslint-plugin-sonarjs';
import promise from 'eslint-plugin-promise';
import stylistic from '@stylistic/eslint-plugin';
import globals from 'globals';

export default [
    {
        files: ['**/*.{js,mjs,cjs}'],
        languageOptions: {
            globals: {
                ...globals.es2021,
                ...globals.nodeBuiltin,
            },
            ecmaVersion: 'latest',
            sourceType: 'module',
        },
        linterOptions: {
            reportUnusedDisableDirectives: 'error',
            reportUnusedInlineConfigs: 'error',
        },
        plugins: {
            unicorn,
            ava,
            n,
            noNative,
            comments,
            sonarjs,
            promise,
            stylistic,
        },
        rules: {
            // unicorn:
            'unicorn/better-regex': 'error',
            'unicorn/catch-error-name': 'off',
            'unicorn/consistent-assert': 'warn',
            'unicorn/consistent-date-clone': 'error',
            'unicorn/consistent-destructuring': 'off',
            'unicorn/consistent-empty-array-spread': 'error',
            'unicorn/consistent-existence-index-check': 'error',
            'unicorn/consistent-function-scoping': 'error',
            'unicorn/custom-error-definition': 'error',
            'unicorn/empty-brace-spaces': 'error',
            'unicorn/error-message': 'error',
            'unicorn/escape-case': 'error',
            'unicorn/expiring-todo-comments': 'off',
            'unicorn/explicit-length-check': 'error',
            'unicorn/filename-case': 'off',
            'unicorn/import-style': 'off',
            'unicorn/new-for-builtins': 'error',
            'unicorn/no-abusive-eslint-disable': 'off',
            'unicorn/no-accessor-recursion': 'error',
            'unicorn/no-anonymous-default-export': 'off',
            'unicorn/no-array-callback-reference': 'off',
            'unicorn/no-array-for-each': 'error',
            'unicorn/no-array-method-this-argument': 'error',
            // 'unicorn/no-array-push-push': 'error', //prefer-single-call
            'unicorn/no-array-reduce': 'off',
            'unicorn/no-array-reverse': ['error', {allowExpressionStatement: false}],
            'unicorn/no-await-expression-member': 'error',
            'unicorn/no-await-in-promise-methods': 'error',
            'unicorn/no-console-spaces': 'error',
            'unicorn/no-document-cookie': 'off',
            'unicorn/no-empty-file': 'off',
            'unicorn/no-for-loop': 'error',
            'unicorn/no-hex-escape': 'off',
            // 'unicorn/no-instanceof-array': 'error', //no-instanceof-builtins
            'unicorn/no-instanceof-builtins': 'error',
            'unicorn/no-invalid-fetch-options': 'off',
            'unicorn/no-invalid-remove-event-listener': 'error',
            'unicorn/no-keyword-prefix': 'off',
            'unicorn/no-lonely-if': 'error',
            'unicorn/no-magic-array-flat-depth': 'off',
            'unicorn/no-named-default': 'error',
            'unicorn/no-negated-condition': 'error',
            'unicorn/no-negation-in-equality-check': 'error',
            'unicorn/no-nested-ternary': 'off',
            'unicorn/no-new-array': 'off',
            'unicorn/no-new-buffer': 'error',
            'unicorn/no-null': 'off',
            'unicorn/no-object-as-default-parameter': 'error',
            'unicorn/no-process-exit': 'error',
            'unicorn/no-single-promise-in-promise-methods': 'error',
            'unicorn/no-static-only-class': 'error',
            'unicorn/no-thenable': 'error',
            'unicorn/no-this-assignment': 'error',
            'unicorn/no-typeof-undefined': ['error', {checkGlobalVariables: true}],
            'unicorn/no-unnecessary-array-flat-depth': 'error',
            'unicorn/no-unnecessary-array-splice-count': 'error',
            'unicorn/no-unnecessary-await': 'error',
            'unicorn/no-unnecessary-polyfills': 'error',
            'unicorn/no-unnecessary-slice-end': 'error',
            'unicorn/no-unreadable-array-destructuring': 'off',
            'unicorn/no-unreadable-iife': 'error',
            'unicorn/no-unused-properties': 'off',
            'unicorn/no-useless-error-capture-stack-trace': 'error',
            'unicorn/no-useless-fallback-in-spread': 'error',
            'unicorn/no-useless-length-check': 'error',
            'unicorn/no-useless-promise-resolve-reject': 'error',
            'unicorn/no-useless-spread': 'error',
            'unicorn/no-useless-switch-case': 'error',
            'unicorn/no-useless-undefined': 'error',
            'unicorn/no-zero-fractions': 'error',
            'unicorn/number-literal-case': 'error',
            'unicorn/numeric-separators-style': ['error', {onlyIfContainsSeparator: true}],
            'unicorn/prefer-add-event-listener': 'off',
            'unicorn/prefer-array-find': 'error',
            'unicorn/prefer-array-flat': 'error',
            'unicorn/prefer-array-flat-map': 'error',
            'unicorn/prefer-array-index-of': 'error',
            'unicorn/prefer-array-some': 'error',
            'unicorn/prefer-at': 'error',
            'unicorn/prefer-blob-reading-methods': 'error',
            'unicorn/prefer-class-fields': 'error',
            'unicorn/prefer-code-point': 'error',
            'unicorn/prefer-date-now': 'error',
            'unicorn/prefer-default-parameters': 'error',
            'unicorn/prefer-dom-node-append': 'off',
            'unicorn/prefer-dom-node-dataset': 'off',
            'unicorn/prefer-dom-node-remove': 'off',
            'unicorn/prefer-dom-node-text-content': 'off',
            'unicorn/prefer-event-target': 'error',
            'unicorn/prefer-export-from': 'error',
            'unicorn/prefer-global-this': 'error',
            'unicorn/prefer-import-meta-properties': 'error',
            'unicorn/prefer-includes': 'error',
            'unicorn/prefer-json-parse-buffer': 'error',
            'unicorn/prefer-keyboard-event-key': 'off',
            'unicorn/prefer-logical-operator-over-ternary': 'error',
            'unicorn/prefer-math-min-max': 'error',
            'unicorn/prefer-math-trunc': 'off',
            'unicorn/prefer-modern-dom-apis': 'off',
            'unicorn/prefer-modern-math-apis': 'off',
            'unicorn/prefer-module': 'error',
            'unicorn/prefer-native-coercion-functions': 'error',
            'unicorn/prefer-negative-index': 'error',
            'unicorn/prefer-node-protocol': 'error',
            'unicorn/prefer-number-properties': 'error',
            'unicorn/prefer-object-from-entries': 'error',
            'unicorn/prefer-optional-catch-binding': 'error',
            'unicorn/prefer-prototype-methods': 'error',
            'unicorn/prefer-query-selector': 'error',
            'unicorn/prefer-reflect-apply': 'error',
            'unicorn/prefer-regexp-test': 'off',
            'unicorn/prefer-set-has': 'off',
            'unicorn/prefer-set-size': 'off',
            'unicorn/prefer-single-call': 'error',
            'unicorn/prefer-spread': 'error',
            'unicorn/prefer-string-raw': 'off',
            'unicorn/prefer-string-replace-all': 'error',
            'unicorn/prefer-string-slice': 'error',
            'unicorn/prefer-string-starts-ends-with': 'error',
            'unicorn/prefer-string-trim-start-end': 'error',
            'unicorn/prefer-structured-clone': 'error',
            'unicorn/prefer-switch': 'off',
            'unicorn/prefer-ternary': 'error',
            'unicorn/prefer-top-level-await': 'error',
            'unicorn/prefer-type-error': 'error',
            'unicorn/prevent-abbreviations': 'off',
            'unicorn/relative-url-style': 'error',
            'unicorn/require-array-join-separator': 'error',
            'unicorn/require-module-specifiers': 'error',
            'unicorn/require-number-to-fixed-digits-argument': 'off',
            'unicorn/require-post-message-target-origin': 'off',
            'unicorn/string-content': 'off',
            'unicorn/switch-case-braces': 'off',
            'unicorn/template-indent': 'off',
            'unicorn/text-encoding-identifier-case': 'error',
            'unicorn/throw-new-error': 'error',

            // ava:
            'ava/assertion-arguments': 'error',
            'ava/hooks-order': 'off',
            'ava/max-asserts': 'off',
            'ava/no-async-fn-without-await': 'error',
            'ava/no-duplicate-modifiers': 'error',
            'ava/no-identical-title': 'error',
            'ava/no-ignored-test-files': 'error',
            'ava/no-import-test-files': 'error',
            'ava/no-incorrect-deep-equal': 'error',
            'ava/no-inline-assertions': 'error',
            'ava/no-nested-tests': 'error',
            'ava/no-only-test': 'warn',
            'ava/no-skip-assert': 'warn',
            'ava/no-skip-test': 'warn',
            'ava/no-todo-implementation': 'error',
            'ava/no-todo-test': 'warn',
            'ava/no-unknown-modifiers': 'error',
            'ava/prefer-async-await': 'error',
            'ava/prefer-power-assert': 'off',
            'ava/prefer-t-regex': 'error',
            'ava/test-title': 'error',
            'ava/test-title-format': 'off',
            'ava/use-t': 'error',
            'ava/use-t-throws-async-well': 'off',
            'ava/use-t-well': 'error',
            'ava/use-test': 'error',
            'ava/use-true-false': 'error',

            // n:
            'n/callback-return': 'off',
            'n/exports-style': 'error',
            'n/file-extension-in-import': 'error',
            'n/global-require': 'error',
            'n/handle-callback-err': 'off',
            'n/hashbang': 'error',
            'n/no-callback-literal': 'off',
            'n/no-deprecated-api': 'warn',
            'n/no-exports-assign': 'error',
            'n/no-extraneous-import': 'error',
            'n/no-extraneous-require': 'error',
            'n/no-missing-import': 'error',
            'n/no-missing-require': 'error',
            'n/no-mixed-requires': 'off',
            'n/no-new-require': 'error',
            'n/no-path-concat': 'error',
            'n/no-process-env': 'off',
            'n/no-process-exit': 'off',
            'n/no-restricted-import': 'off',
            'n/no-restricted-require': 'off',
            'n/no-sync': 'off',
            'n/no-top-level-await': 'off',
            'n/no-unpublished-bin': 'error',
            'n/no-unpublished-import': 'error',
            'n/no-unpublished-require': 'error',
            'n/no-unsupported-features/es-builtins': 'warn',
            'n/no-unsupported-features/es-syntax': 'warn',
            'n/no-unsupported-features/node-builtins': 'warn',
            'n/prefer-global/buffer': 'error',
            'n/prefer-global/console': 'error',
            'n/prefer-global/process': 'error',
            'n/prefer-global/text-decoder': 'error',
            'n/prefer-global/text-encoder': 'error',
            'n/prefer-global/url': 'error',
            'n/prefer-global/url-search-params': 'error',
            'n/prefer-node-protocol': 'off',
            'n/prefer-promises/dns': 'error',
            'n/prefer-promises/fs': 'error',
            'n/process-exit-as-throw': 'error',

            // no-use-extend-native:
            'noNative/no-use-extend-native': 'warn',

            // eslint-comments:
            'comments/disable-enable-pair': ['error', {allowWholeFile: true}],
            'comments/no-aggregating-enable': 'error',
            'comments/no-duplicate-disable': 'error',
            'comments/no-unlimited-disable': 'error',
            'comments/no-unused-disable': 'error',
            'comments/no-unused-enable': 'error',
            'comments/no-restricted-disable': 'off',
            'comments/no-use': 'off',
            'comments/require-description': 'off',

            // sonarjs:
            'sonarjs/arguments-usage': 'off',
            'sonarjs/array-constructor': 'off',
            'sonarjs/arrow-function-convention': 'off',
            'sonarjs/bitwise-operators': 'off',
            'sonarjs/block-scoped-var': 'off',
            'sonarjs/bool-param-default': 'off',
            'sonarjs/call-argument-line': 'error',
            'sonarjs/class-name': 'error',
            'sonarjs/code-eval': 'off',
            'sonarjs/cognitive-complexity': 'off',
            'sonarjs/comma-or-logical-or-case': 'error',
            'sonarjs/comment-regex': 'off',
            'sonarjs/confidential-information-logging': 'off',
            'sonarjs/constructor-for-side-effects': 'error',
            'sonarjs/content-length': 'off',
            'sonarjs/content-security-policy': 'off',
            'sonarjs/cookie-no-httponly': 'off',
            'sonarjs/cors': 'off',
            'sonarjs/csrf': 'off',
            'sonarjs/cyclomatic-complexity': 'off',
            'sonarjs/declarations-in-global-scope': 'off',
            'sonarjs/destructuring-assignment-syntax': 'error',
            'sonarjs/elseif-without-else': 'off',
            'sonarjs/encryption-secure-mode': 'error',
            'sonarjs/expression-complexity': 'off',
            'sonarjs/file-name-differ-from-class': 'off',
            'sonarjs/file-permissions': 'off',
            'sonarjs/file-uploads': 'off',
            'sonarjs/fixme-tag': 'off',
            'sonarjs/for-in': 'error',
            'sonarjs/for-loop-increment-sign': 'off',
            'sonarjs/frame-ancestors': 'off',
            'sonarjs/function-inside-loop': 'error',
            'sonarjs/function-name': 'off',
            'sonarjs/future-reserved-words': 'off',
            'sonarjs/generator-without-yield': 'error',
            'sonarjs/hashing': 'error',
            'sonarjs/hidden-files': 'off',
            'sonarjs/inconsistent-function-call': 'off',
            'sonarjs/insecure-cookie': 'off',
            'sonarjs/insecure-jwt-token': 'off',
            'sonarjs/inverted-assertion-arguments': 'off',
            'sonarjs/label-position': 'off',
            'sonarjs/link-with-target-blank': 'off',
            'sonarjs/max-lines': 'off',
            'sonarjs/max-lines-per-function': 'off',
            'sonarjs/max-switch-cases': 'off',
            'sonarjs/misplaced-loop-counter': 'off',
            'sonarjs/nested-control-flow': 'off',
            'sonarjs/no-all-duplicated-branches': 'error',
            'sonarjs/no-async-constructor': 'error',
            'sonarjs/no-built-in-override': 'off',
            'sonarjs/no-case-label-in-switch': 'off',
            'sonarjs/no-clear-text-protocols': 'off',
            'sonarjs/no-collapsible-if': 'error',
            'sonarjs/no-commented-code': 'off',
            'sonarjs/no-dead-store': 'error',
            'sonarjs/no-delete-var': 'error',
            'sonarjs/no-duplicate-string': 'off',
            'sonarjs/no-duplicated-branches': 'error',
            'sonarjs/no-element-overwrite': 'error',
            'sonarjs/no-empty-collection': 'off',
            'sonarjs/no-equals-in-for-termination': 'error',
            'sonarjs/no-extra-arguments': 'error',
            'sonarjs/no-fallthrough': 'off',
            'sonarjs/no-function-declaration-in-block': 'error',
            'sonarjs/no-global-this': 'error',
            'sonarjs/no-globals-shadowing': 'off',
            'sonarjs/no-gratuitous-expressions': 'error',
            'sonarjs/no-hardcoded-ip': 'off',
            'sonarjs/no-hardcoded-passwords': 'off',
            'sonarjs/no-hardcoded-secrets': 'off',
            'sonarjs/no-identical-conditions': 'error',
            'sonarjs/no-identical-expressions': 'error',
            'sonarjs/no-identical-functions': 'error',
            'sonarjs/no-ignored-exceptions': 'off',
            'sonarjs/no-implicit-dependencies': 'off',
            'sonarjs/no-implicit-global': 'off',
            'sonarjs/no-inconsistent-returns': 'off',
            'sonarjs/no-internal-api-use': 'off',
            'sonarjs/no-invariant-returns': 'error',
            'sonarjs/no-inverted-boolean-check': 'error',
            'sonarjs/no-labels': 'error',
            'sonarjs/no-literal-call': 'error',
            'sonarjs/no-mixed-content': 'off',
            'sonarjs/no-nested-assignment': 'error',
            'sonarjs/no-nested-conditional': 'off',
            'sonarjs/no-nested-functions': 'off',
            'sonarjs/no-nested-incdec': 'error',
            'sonarjs/no-nested-switch': 'off',
            'sonarjs/no-nested-template-literals': 'error',
            'sonarjs/no-one-iteration-loop': 'error',
            'sonarjs/no-os-command-from-path': 'off',
            'sonarjs/no-parameter-reassignment': 'off',
            'sonarjs/no-primitive-wrappers': 'error',
            'sonarjs/no-redundant-assignments': 'error',
            'sonarjs/no-redundant-boolean': 'error',
            'sonarjs/no-redundant-jump': 'error',
            'sonarjs/no-reference-error': 'off',
            'sonarjs/no-same-line-conditional': 'error',
            'sonarjs/no-small-switch': 'error',
            'sonarjs/no-undefined-assignment': 'off',
            'sonarjs/no-unenclosed-multiline-block': 'off',
            'sonarjs/no-unthrown-error': 'error',
            'sonarjs/no-unused-collection': 'error',
            'sonarjs/no-unused-function-argument': 'off',
            'sonarjs/no-unused-vars': 'off',
            'sonarjs/no-use-of-empty-return-value': 'error',
            'sonarjs/no-useless-catch': 'off',
            'sonarjs/no-useless-increment': 'error',
            'sonarjs/no-variable-usage-before-declaration': 'off',
            'sonarjs/no-weak-cipher': 'error',
            'sonarjs/no-weak-keys': 'error',
            'sonarjs/no-wildcard-import': 'error',
            'sonarjs/non-existent-operator': 'error',
            'sonarjs/os-command': 'off',
            'sonarjs/prefer-default-last': 'off',
            'sonarjs/prefer-immediate-return': 'error',
            'sonarjs/prefer-object-literal': 'off',
            'sonarjs/prefer-promise-shorthand': 'error',
            'sonarjs/prefer-single-boolean-return': 'error',
            'sonarjs/prefer-while': 'error',
            'sonarjs/production-debug': 'off',
            'sonarjs/pseudo-random': 'off',
            'sonarjs/public-static-readonly': 'error',
            'sonarjs/shorthand-property-grouping': 'off',
            'sonarjs/stateful-regex': 'error',
            'sonarjs/super-invocation': 'error',
            'sonarjs/todo-tag': 'off',
            'sonarjs/too-many-break-or-continue-in-loop': 'off',
            'sonarjs/unverified-certificate': 'off',
            'sonarjs/updated-const-var': 'off',
            'sonarjs/variable-name': 'off',
            'sonarjs/weak-ssl': 'error',
            'sonarjs/x-powered-by': 'error',

            // promise:
            'promise/always-return': 'warn',
            'promise/avoid-new': 'off',
            'promise/catch-or-return': 'error',
            'promise/no-callback-in-promise': 'off',
            'promise/no-multiple-resolved': 'off',
            'promise/no-native': 'off',
            'promise/no-nesting': 'warn',
            'promise/no-new-statics': 'error',
            'promise/no-promise-in-callback': 'off',
            'promise/no-return-in-finally': 'error',
            'promise/no-return-wrap': 'error',
            'promise/param-names': 'error',
            'promise/prefer-await-to-callbacks': 'off',
            'promise/prefer-await-to-then': 'off',
            'promise/prefer-catch': 'off',
            'promise/spec-only': 'error',
            'promise/valid-params': 'error',

            // @stylistic/eslint-plugin

            'stylistic/array-bracket-newline': 'error',
            'stylistic/array-bracket-spacing': 'error',
            'stylistic/array-element-newline': 'off',
            'stylistic/arrow-parens': ['error', 'as-needed'],
            'stylistic/arrow-spacing': 'error',
            'stylistic/block-spacing': ['error', 'never'],
            'stylistic/brace-style': ['error', '1tbs', {allowSingleLine: true}],
            'stylistic/comma-dangle': ['error', 'always-multiline'],
            'stylistic/comma-spacing': 'error',
            'stylistic/comma-style': 'error',
            'stylistic/computed-property-spacing': 'error',
            'stylistic/curly-newline': 'off',
            'stylistic/dot-location': ['error', 'property'],
            'stylistic/eol-last': 'error',
            'stylistic/function-call-argument-newline': 'off',
            'stylistic/function-call-spacing': 'error',
            'stylistic/function-paren-newline': 'error',
            'stylistic/generator-star-spacing': 'error',
            'stylistic/implicit-arrow-linebreak': 'error',
            'stylistic/indent': 'error',
            'stylistic/indent-binary-ops': 'off',
            'stylistic/jsx-quotes': 'error',
            'stylistic/key-spacing': 'error',
            'stylistic/keyword-spacing': ['error', {overrides: {if: {after: false}, for: {after: false}, while: {after: false}}}],
            'stylistic/line-comment-position': 'off',
            'stylistic/linebreak-style': 'error',
            'stylistic/lines-around-comment': 'off',
            'stylistic/lines-between-class-members': 'off',
            'stylistic/max-len': 'off',
            'stylistic/max-statements-per-line': 'off',
            'stylistic/multiline-comment-style': 'off',
            'stylistic/multiline-ternary': 'off',
            'stylistic/new-parens': 'error',
            'stylistic/newline-per-chained-call': 'off',
            'stylistic/no-confusing-arrow': 'off',
            'stylistic/no-extra-parens': 'error',
            'stylistic/no-extra-semi': 'error',
            'stylistic/no-floating-decimal': 'error',
            'stylistic/no-mixed-operators': 'off',
            'stylistic/no-mixed-spaces-and-tabs': 'error',
            'stylistic/no-multi-spaces': ['error', {ignoreEOLComments: true}],
            'stylistic/no-multiple-empty-lines': ['error', {max: 1}],
            'stylistic/no-tabs': 'error',
            'stylistic/no-trailing-spaces': 'error',
            'stylistic/no-whitespace-before-property': 'error',
            'stylistic/nonblock-statement-body-position': 'error',
            'stylistic/object-curly-newline': ['error', {multiline: true}],
            'stylistic/object-curly-spacing': 'error',
            'stylistic/object-property-newline': 'off',
            'stylistic/one-var-declaration-per-line': ['error', 'always'],
            'stylistic/operator-linebreak': 'error',
            'stylistic/padded-blocks': ['error', 'never'],
            'stylistic/padding-line-between-statements': 'off',
            'stylistic/quote-props': ['error', 'as-needed'],
            'stylistic/quotes': ['error', 'single', {allowTemplateLiterals: 'always', avoidEscape: true}],
            'stylistic/rest-spread-spacing': 'error',
            'stylistic/semi': 'error',
            'stylistic/semi-spacing': 'error',
            'stylistic/semi-style': 'error',
            'stylistic/space-before-blocks': ['error', 'never'],
            'stylistic/space-before-function-paren': ['error', {anonymous: 'never', named: 'never', asyncArrow: 'always', catch: 'never'}],
            'stylistic/space-in-parens': 'error',
            'stylistic/space-infix-ops': 'error',
            'stylistic/space-unary-ops': 'error',
            'stylistic/spaced-comment': 'off',
            'stylistic/switch-colon-spacing': 'error',
            'stylistic/template-curly-spacing': 'error',
            'stylistic/template-tag-spacing': 'error',
            'stylistic/wrap-iife': ['error', 'inside', {functionPrototypeMethods: true}],
            'stylistic/wrap-regex': 'off',
            'stylistic/yield-star-spacing': 'error',

            // CORE Eslint rules:

            // Possible Problems
            'array-callback-return': ['error', {checkForEach: true}],
            'constructor-super': 'error',
            'for-direction': 'error',
            'getter-return': 'error',
            'no-async-promise-executor': 'error',
            'no-await-in-loop': 'error',
            'no-class-assign': 'error',
            'no-compare-neg-zero': 'error',
            'no-cond-assign': ['error', 'always'],
            'no-const-assign': 'error',
            'no-constant-binary-expression': 'error',
            'no-constant-condition': 'error',
            'no-constructor-return': 'error',
            'no-control-regex': 'error',
            'no-debugger': 'error',
            'no-dupe-args': 'error',
            'no-dupe-class-members': 'error',
            'no-dupe-else-if': 'error',
            'no-dupe-keys': 'error',
            'no-duplicate-case': 'error',
            'no-duplicate-imports': ['error', {includeExports: true}],
            'no-empty-character-class': 'error',
            'no-empty-pattern': 'error',
            'no-ex-assign': 'error',
            'no-fallthrough': 'error',
            'no-func-assign': 'error',
            'no-import-assign': 'error',
            'no-inner-declarations': 'error',
            'no-invalid-regexp': 'error',
            'no-irregular-whitespace': 'error',
            'no-loss-of-precision': 'error',
            'no-misleading-character-class': 'error',
            'no-new-native-nonconstructor': 'error',
            'no-obj-calls': 'error',
            'no-promise-executor-return': 'error',
            'no-prototype-builtins': 'error',
            'no-self-assign': ['error', {props: true}],
            'no-self-compare': 'error',
            'no-setter-return': 'error',
            'no-sparse-arrays': 'error',
            'no-template-curly-in-string': 'error',
            'no-this-before-super': 'error',
            'no-unassigned-vars': 'error',
            'no-undef': ['error', {typeof: true}],
            'no-unexpected-multiline': 'error',
            'no-unmodified-loop-condition': 'error',
            'no-unreachable': 'error',
            'no-unreachable-loop': 'error',
            'no-unsafe-finally': 'error',
            'no-unsafe-negation': ['error', {enforceForOrderingRelations: true}],
            'no-unsafe-optional-chaining': 'error',
            'no-unused-private-class-members': 'error',
            'no-unused-vars': 'error',
            'no-use-before-define': 'error',
            'no-useless-assignment': 'error',
            'no-useless-backreference': 'error',
            'require-atomic-updates': 'error',
            'use-isnan': ['error', {enforceForIndexOf: true}],
            'valid-typeof': ['error', {requireStringLiterals: true}],

            // Suggestions
            'accessor-pairs': 'off',
            'arrow-body-style': 'error',
            'block-scoped-var': 'error',
            camelcase: 'off',
            'capitalized-comments': 'off',
            'class-methods-use-this': 'error',
            complexity: 'off',
            'consistent-return': 'error',
            'consistent-this': 'off',
            curly: ['error', 'multi-line'],
            'default-case': 'error',
            'default-case-last': 'error',
            'default-param-last': 'error',
            'dot-notation': 'error',
            eqeqeq: 'error',
            'func-name-matching': 'error',
            'func-names': ['error', 'never'],
            'func-style': 'off',
            'grouped-accessor-pairs': 'error',
            'guard-for-in': 'error',
            'id-denylist': 'off',
            'id-length': 'off',
            'id-match': 'off',
            'init-declarations': 'error',
            'logical-assignment-operators': 'off',
            'max-classes-per-file': 'off',
            'max-depth': 'off',
            'max-lines': 'off',
            'max-lines-per-function': 'off',
            'max-nested-callbacks': 'off',
            'max-params': 'off',
            'max-statements': 'off',
            'new-cap': ['error', {capIsNew: false}],
            'no-alert': 'error',
            'no-array-constructor': 'error',
            'no-bitwise': 'warn',
            'no-caller': 'error',
            'no-case-declarations': 'error',
            'no-console': 'warn',
            'no-continue': 'error',
            'no-delete-var': 'error',
            'no-div-regex': 'error',
            'no-else-return': 'error',
            'no-empty': ['error', {allowEmptyCatch: true}],
            'no-empty-function': 'warn',
            'no-empty-static-block': 'error',
            'no-eq-null': 'error',
            'no-eval': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-extra-boolean-cast': ['error', {enforceForInnerExpressions: true}],
            'no-extra-label': 'error',
            'no-global-assign': 'error',
            'no-implicit-coercion': 'off',
            'no-implicit-globals': 'error',
            'no-implied-eval': 'error',
            'no-inline-comments': 'off',
            'no-invalid-this': 'error',
            'no-iterator': 'error',
            'no-label-var': 'error',
            'no-labels': 'error',
            'no-lone-blocks': 'error',
            'no-lonely-if': 'error',
            'no-loop-func': 'error',
            'no-magic-numbers': 'off',
            'no-multi-assign': 'error',
            'no-multi-str': 'error',
            'no-negated-condition': 'off',
            'no-nested-ternary': 'off',
            'no-new': 'error',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-nonoctal-decimal-escape': 'off',
            'no-object-constructor': 'error',
            'no-octal': 'error',
            'no-octal-escape': 'error',
            'no-param-reassign': ['warn', {props: true, ignorePropertyModificationsFor: ['e', 'err', 'error']}],
            'no-plusplus': 'off',
            'no-proto': 'error',
            'no-redeclare': 'error',
            'no-regex-spaces': 'error',
            'no-restricted-exports': 'off',
            'no-restricted-globals': 'off',
            'no-restricted-imports': 'off',
            'no-restricted-properties': 'off',
            'no-restricted-syntax': 'off',
            'no-return-assign': ['error', 'always'],
            'no-script-url': 'error',
            'no-sequences': 'error',
            'no-shadow': 'off',
            'no-shadow-restricted-names': 'error',
            'no-ternary': 'off',
            'no-throw-literal': 'error',
            'no-undef-init': 'error',
            'no-undefined': 'off',
            'no-underscore-dangle': 'off',
            'no-unneeded-ternary': 'error',
            'no-unused-expressions': 'error',
            'no-unused-labels': 'error',
            'no-useless-call': 'error',
            'no-useless-catch': 'error',
            'no-useless-computed-key': 'error',
            'no-useless-concat': 'error',
            'no-useless-constructor': 'error',
            'no-useless-escape': 'error',
            'no-useless-rename': 'error',
            'no-useless-return': 'error',
            'no-var': 'error',
            'no-void': 'error',
            'no-warning-comments': 'off',
            'no-with': 'error',
            'object-shorthand': 'error',
            'one-var': ['error', 'never'],
            'operator-assignment': 'error',
            'prefer-arrow-callback': 'error',
            'prefer-const': 'warn',
            'prefer-destructuring': 'off',
            'prefer-exponentiation-operator': 'error',
            'prefer-named-capture-group': 'off',
            'prefer-numeric-literals': 'error',
            'prefer-object-has-own': 'error',
            'prefer-object-spread': 'error',
            'prefer-promise-reject-errors': ['error', {allowEmptyReject: true}],
            'prefer-regex-literals': ['error', {disallowRedundantWrapping: true}],
            'prefer-rest-params': 'error',
            'prefer-spread': 'error',
            'prefer-template': 'error',
            radix: 'error',
            'require-await': 'error',
            'require-unicode-regexp': 'off',
            'require-yield': 'error',
            'sort-imports': 'off',
            'sort-keys': 'off',
            'sort-vars': 'off',
            strict: 'error',
            'symbol-description': 'error',
            'vars-on-top': 'error',
            yoda: 'error',

            // Layout & Formatting
            'unicode-bom': 'error',
        },
    },
];
