module.exports = {

    parserOptions: {
        ecmaVersion: 2017,
        sourceType: 'module',
        ecmaFeatures: {
            jsx: true,
            experimentalObjectRestSpread: true,
        },
    },
    env: {
        node: true,
        es6: true,
    },
    rules: {
        'comma-dangle': [
            'error',
            'always-multiline',
        ],
        'for-direction': 'error',
        'getter-return': 'error',
        'no-await-in-loop': 'error',
        'no-compare-neg-zero': 'error',
        'no-cond-assign': 'error',
        'no-console': 'warn',
        'no-constant-condition': 'error',
        'no-control-regex': 'error',
        'no-debugger': 'error',
        'no-dupe-args': 'error',
        'no-dupe-keys': 'error',
        'no-duplicate-case': 'error',
        'no-empty-character-class': 'error',
        'no-empty': [
            'error',
            {allowEmptyCatch: true},
        ],
        'no-ex-assign': 'error',
        'no-extra-boolean-cast': 'error',
        'no-extra-parens': 'error',
        'no-extra-semi': 'error',
        'no-func-assign': 'error',
        'no-inner-declarations': 'error',
        'no-invalid-regexp': 'error',
        'no-irregular-whitespace': 'error',
        'no-obj-calls': 'error',
        'no-prototype-builtins': 'error',
        'no-regex-spaces': 'error',
        'no-sparse-arrays': 'error',
        'no-template-curly-in-string': 'error',
        'no-unreachable': 'error',
        'no-unsafe-finally': 'error',
        'no-unsafe-negation': 'error',
        'use-isnan': 'error',
        'valid-typeof': [
            'error',
            {requireStringLiterals: true},
        ],
        'no-unexpected-multiline': 'error',
        'array-callback-return': 'error',
        curly: [
            'error',
            'multi-line',
        ],
        'default-case': 'error',
        'dot-notation': 'error',
        'dot-location': [
            'error',
            'property',
        ],
        eqeqeq: 'error',
        'guard-for-in': 'error',
        'no-alert': 'error',
        'no-caller': 'error',
        'no-case-declarations': 'error',
        'no-div-regex': 'error',
        'no-else-return': 'error',
        'no-empty-pattern': 'error',
        'no-eval': 'error',
        'no-extend-native': 'error',
        'no-extra-bind': 'error',
        'no-fallthrough': 'error',
        'no-floating-decimal': 'error',
        'no-global-assign': 'error',
        'no-implicit-globals': 'error',
        'no-implied-eval': 'error',
        'no-iterator': 'error',
        'no-labels': 'error',
        'no-lone-blocks': 'error',
        'no-multi-spaces': 'error',
        'no-multi-str': 'error',
        'no-new-func': 'error',
        'no-new-wrappers': 'error',
        'no-new': 'error',
        'no-octal-escape': 'error',
        'no-octal': 'error',
        'no-proto': 'error',
        'no-redeclare': 'error',
        'no-return-assign': [
            'error',
            'always',
        ],
        'no-return-await': 'error',
        'no-script-url': 'error',
        'no-self-assign': [
            'error',
            {props: true},
        ],
        'no-self-compare': 'error',
        'no-sequences': 'error',
        'no-throw-literal': 'error',
        'no-unmodified-loop-condition': 'error',
        'no-unused-expressions': 'error',
        'no-useless-call': 'error',
        'no-useless-concat': 'error',
        'no-useless-escape': 'error',
        'no-useless-return': 'error',
        'no-void': 'error',
        'no-warning-comments': 'warn',
        'no-with': 'error',
        'prefer-promise-reject-errors': [
            'error',
            {allowEmptyReject: true},
        ],
        radix: 'error',
        'require-await': 'error',
        'wrap-iife': [
            'error',
            'inside',
            {functionPrototypeMethods: true},
        ],
        yoda: 'error',
        strict: [
            'error',
            'never',
        ],
        'no-delete-var': 'error',
        'no-restricted-globals': [
            'error',
            'event',
        ],
        'no-shadow-restricted-names': 'error',
        'no-undef-init': 'error',
        'no-undef': [
            'error',
            {typeof: true},
        ],
        'no-unused-vars': [
            'error',
            {
                ignoreRestSiblings: true,
                args: 'none',
                argsIgnorePattern: '^_$',
            },
        ],
        'no-use-before-define': [
            'error',
            'nofunc',
        ],
        'callback-return': [
            'warn',
            [
                'cb',
                'callback',
                'next',
                'done',
            ],
        ],
        'handle-callback-err': 'warn',
        'no-buffer-constructor': 'error',
        'no-new-require': 'error',
        'no-path-concat': 'error',
        'no-restricted-imports': [
            'error',
            'domain',
            'freelist',
            'smalloc',
            'sys',
            'colors',
        ],
        'no-restricted-modules': [
            'error',
            'domain',
            'freelist',
            'smalloc',
            'sys',
            'colors',
        ],
        'array-bracket-newline': [
            'error',
            {multiline: true},
        ],
        'array-bracket-spacing': [
            'error',
            'never',
        ],
        'block-spacing': 'error',
        'brace-style': [
            'error',
            '1tbs',
            {allowSingleLine: true},
        ],
        camelcase: [
            'error',
            {properties: 'always'},
        ],
        'comma-spacing': [
            'error',
            {
                before: false,
                after: true,
            },
        ],
        'comma-style': [
            'error',
            'last',
        ],
        'computed-property-spacing': [
            'error',
            'never',
        ],
        'eol-last': 'error',
        'func-call-spacing': [
            'error',
            'never',
        ],
        'func-name-matching': 'error',
        'func-names': [
            'error',
            'never',
        ],
        'function-paren-newline': [
            'error',
            'multiline',
        ],
        indent: [
            'error',
            4,
        ],
        'jsx-quotes': 'error',
        'key-spacing': [
            'error',
            {
                beforeColon: false,
                afterColon: true,
            },
        ],
        'keyword-spacing': [
            'error',
            {
                overrides: {
                    catch: {after: false},
                    if: {after: false},
                    for: {after: false},
                    while: {after: false},
                },
            },
        ],
        'linebreak-style': [
            'error',
            'unix',
        ],
        'max-statements-per-line': 'error',
        'new-cap': [
            'error',
            {
                newIsCap: true,
                capIsNew: true,
            },
        ],
        'new-parens': 'error',
        'newline-per-chained-call': [
            'error',
            {ignoreChainWithDepth: 3},
        ],
        'no-array-constructor': 'error',
        'no-bitwise': 'warn',
        'no-continue': 'error',
        'no-lonely-if': 'error',
        'no-multi-assign': 'error',
        'no-multiple-empty-lines': [
            'error',
            {max: 1},
        ],
        'no-negated-condition': 'error',
        'no-new-object': 'error',
        'no-tabs': 'error',
        'no-whitespace-before-property': 'error',
        'no-trailing-spaces': 'error',
        'no-unneeded-ternary': 'error',
        'object-curly-newline': [
            'error',
            {multiline: true},
        ],
        'object-curly-spacing': [
            'error',
            'never',
        ],
        'one-var': [
            'error',
            'never',
        ],
        'one-var-declaration-per-line': 'error',
        'operator-assignment': [
            'error',
            'always',
        ],
        'operator-linebreak': [
            'error',
            'after',
        ],
        'padded-blocks': [
            'error',
            'never',
        ],
        'quote-props': [
            'error',
            'as-needed',
        ],
        quotes: [
            'error',
            'single',
            {allowTemplateLiterals: true},
        ],
        'semi-spacing': [
            'error',
            {
                before: false,
                after: true,
            },
        ],
        'semi-style': [
            'error',
            'last',
        ],
        semi: [
            'error',
            'always',
        ],
        'space-before-blocks': [
            'error',
            'never',
        ],
        'space-before-function-paren': [
            'error',
            {
                anonymous: 'never',
                named: 'never',
                asyncArrow: 'always',
            },
        ],
        'space-in-parens': [
            'error',
            'never',
        ],
        'space-infix-ops': 'error',
        'space-unary-ops': 'error',
        'switch-colon-spacing': [
            'error',
            {
                after: true,
                before: false,
            },
        ],
        'template-tag-spacing': [
            'error',
            'never',
        ],
        'unicode-bom': [
            'error',
            'never',
        ],
        'arrow-body-style': 'error',
        'arrow-parens': [
            'error',
            'as-needed',
        ],
        'arrow-spacing': [
            'error',
            {
                before: true,
                after: true,
            },
        ],
        'constructor-super': 'error',
        'generator-star-spacing': [
            'error',
            'both',
        ],
        'no-class-assign': 'error',
        'no-const-assign': 'error',
        'no-dupe-class-members': 'error',
        'no-duplicate-imports': 'error',
        'no-new-symbol': 'error',
        'no-this-before-super': 'error',
        'no-useless-computed-key': 'error',
        'no-useless-constructor': 'error',
        'no-useless-rename': 'error',
        'no-var': 'error',
        'object-shorthand': 'error',
        'prefer-arrow-callback': 'error',
        'prefer-const': 'warn',
        'prefer-rest-params': 'error',
        'prefer-spread': 'error',
        'prefer-template': 'error',
        'require-yield': 'error',
        'rest-spread-spacing': [
            'error',
            'never',
        ],
        'symbol-description': 'error',
        'template-curly-spacing': 'error',
        'yield-star-spacing': [
            'error',
            'both',
        ],
    },
};
